image:
  registry: docker.io
  repository: bitnami/contour
  tag: 1.27.0-debian-11-r0   # ← multi-arch対応のtag
  architecture: arm64        # ← 明示的にアーキ指定（bitnamiチャートで有効）

envoy:
  image:
    registry: docker.io
    repository: bitnami/envoy
    tag: 1.28.0-debian-11-r0  # ← multi-arch対応
    architecture: arm64

  service:
    type: LoadBalancer
